Added gofmt and golangci-lint

diff --git a/infrastructure/earthly/go/Earthfile b/infrastructure/earthly/go/Earthfile
--- a/infrastructure/earthly/go/Earthfile
+++ b/infrastructure/earthly/go/Earthfile
@@ -38,6 +38,14 @@ UNIT_TEST:
     COPY pkg pkg
     RUN go test ./...
 
+LINT:
+    FUNCTION
+    ARG FILES_TO_FORMAT=$(gofmt -l ./)
+    IF [ ! -z "$FILES_TO_FORMAT" ]
+        RUN echo "Formatting required for:\n$FILES_TO_FORMAT\nRun \"go fmt ./...\" to fix the errors" && exit 1
+    END
+    RUN golangci-lint run -j4 ./...
+
 DOCKER:
     FUNCTION
     ARG UID=1000
