up

diff --git a/.github/workflows/ci-realibilty-snippet.yml b/.github/workflows/ci-realibilty-snippet.yml
--- a/.github/workflows/ci-realibilty-snippet.yml
+++ b/.github/workflows/ci-realibilty-snippet.yml
@@ -47,60 +47,60 @@ on:
         type: boolean
 
 jobs:
-  # introduce-changes:
-  #   name: Introduce changes
-  #   permissions:
-  #     contents: write
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v6
-  #       with:
-  #         fetch-depth: 0
-  #     - name: Prepare testing branch
-  #       run: |
-  #         # delete existing testing branch
-  #         git push origin --delete ${{ inputs.source_branch }} || true
+  introduce-changes:
+    name: Introduce changes
+    permissions:
+      contents: write
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+      - name: Prepare testing branch
+        run: |
+          # delete existing testing branch
+          git push origin --delete ${{ inputs.source_branch }} || true
 
-  #         # create testing branch with changes
-  #         git checkout ${{ inputs.base_branch }}
-  #         git checkout -b ${{ inputs.source_branch }}
-  #     - name: Modify pkg
-  #       if: inputs.modify_pkg == true
-  #       run: |
-  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> pkg/api/api.go
-  #     - name: Modify cd-service
-  #       if: inputs.modify_cd_service == true
-  #       run: |
-  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/cd-service/cmd/server/main.go
-  #     - name: Modify frontend-service
-  #       if: inputs.modify_frontend_service == true
-  #       run: |
-  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/frontend-service/cmd/server/main.go
-  #     - name: Modify export-service
-  #       if: inputs.modify_export_service == true
-  #       run: |
-  #         echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/manifest-repo-export-service/cmd/server/main.go
-  #     - name: Commit changes
-  #       run: |
-  #         git config user.name "github-actions[bot]"
-  #         git config user.email "github-actions[bot]@users.noreply.github.com"
-  #         git add .
-  #         git commit -m "Automated: Test CI realibility for ${{ inputs.source_branch }}"
-  #         git push origin ${{ inputs.source_branch }}
-  #       env:
-  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  # trigger-ci:
-  #   name: Trigger CI build with specific ref
-  #   needs: [introduce-changes]
-  #   uses: ./.github/workflows/execution-plan-snippet.yml
-  #   with:
-  #     trigger: pull-request
-  #     ref: ${{ inputs.source_branch }}
-  #     skip_unversioned_builds: true
-  #   secrets: inherit
+          # create testing branch with changes
+          git checkout ${{ inputs.base_branch }}
+          git checkout -b ${{ inputs.source_branch }}
+      - name: Modify pkg
+        if: inputs.modify_pkg == true
+        run: |
+          echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> pkg/api/api.go
+      - name: Modify cd-service
+        if: inputs.modify_cd_service == true
+        run: |
+          echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/cd-service/cmd/server/main.go
+      - name: Modify frontend-service
+        if: inputs.modify_frontend_service == true
+        run: |
+          echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/frontend-service/cmd/server/main.go
+      - name: Modify export-service
+        if: inputs.modify_export_service == true
+        run: |
+          echo -e "\nfunc TestCIRealibility_$(date +%s%6N)() {}" >> services/manifest-repo-export-service/cmd/server/main.go
+      - name: Commit changes
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add .
+          git commit -m "Automated: Test CI realibility for ${{ inputs.source_branch }}"
+          git push origin ${{ inputs.source_branch }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  trigger-ci:
+    name: Trigger CI build with specific ref
+    needs: [introduce-changes]
+    uses: ./.github/workflows/execution-plan-snippet.yml
+    with:
+      trigger: pull-request
+      ref: ${{ inputs.source_branch }}
+      skip_unversioned_builds: true
+    secrets: inherit
   check-new-image:
     name: "Check newly built image on registry"
-    # needs: [trigger-ci]
+    needs: [trigger-ci]
     runs-on: ubuntu-latest
     outputs:
       failed_results: ${{ steps.collect-failed-results.outputs.failed_results }}
@@ -119,8 +119,6 @@ jobs:
           echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
       - name: Check newly built image for cd-service
         run: |
-          #IMAGE_TAG="pr-v13.44.13-1-gbc6b7947"
-          IMAGE_TAG="main"
           IMAGE_NAME="europe-west3-docker.pkg.dev/fdc-public-docker-registry/kuberpult/kuberpult-cd-service"
           MAIN_IMAGE_DIGEST="$(skopeo inspect -f '{{.Digest}}' docker://$IMAGE_NAME:main)"
           NEW_IMAGE_DIGEST="$(skopeo inspect -f '{{.Digest}}' docker://$IMAGE_NAME:$IMAGE_TAG 2>/dev/null)"
@@ -138,7 +136,7 @@ jobs:
         id: collect-failed-results
         run: |
           echo "FAILED_RESULTS=$FAILED_RESULTS" >> $GITHUB_OUTPUT
-          echo "Failed results: $FAILED_RESULTS"
+          echo -e "Failed results: $FAILED_RESULTS"
           
         
           
