test

diff --git a/.github/workflows/ci-reliability.yml b/.github/workflows/ci-reliability.yml
--- a/.github/workflows/ci-reliability.yml
+++ b/.github/workflows/ci-reliability.yml
@@ -85,9 +85,10 @@ jobs:
           EMOJI_RESULT_CI_TEST_2="✅"
           EMOJI_RESULT_CI_TEST_3="✅"
 
-          VALIDATION_ERRORS_CI_TEST_1="$(cat validation-errors-1/validation-errors.txt)"
-          VALIDATION_ERRORS_CI_TEST_2="$(cat validation-errors-2/validation-errors.txt)"
-          VALIDATION_ERRORS_CI_TEST_3="$(cat validation-errors-3/validation-errors.txt)"
+          # If the validation-errors artifact is not uploaded, it means the CI test failed
+          VALIDATION_ERRORS_CI_TEST_1=$(cat validation-errors-1/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI test")
+          VALIDATION_ERRORS_CI_TEST_2=$(cat validation-errors-2/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI test")
+          VALIDATION_ERRORS_CI_TEST_3=$(cat validation-errors-3/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI test")
           echo "Validation errors 1: $VALIDATION_ERRORS_CI_TEST_1"
           echo "Validation errors 2: $VALIDATION_ERRORS_CI_TEST_2"
           echo "Validation errors 3: $VALIDATION_ERRORS_CI_TEST_3"
@@ -105,12 +106,6 @@ jobs:
           if [[ "${{ needs.ci-test.result }}" != "success" ]] || [[ -n "$VALIDATION_ERRORS_CI_TEST_3" ]]; then
             EMOJI_RESULT_CI_TEST_3="❌"
             EMOJI_RESULT_OVERALL="❌"
-          fi  
-
-          if [[ "${{ needs.ci-test.result }}" != "success" ]]; then
-            VALIDATION_ERRORS_CI_TEST_1="\nError occurred during CI test"
-            VALIDATION_ERRORS_CI_TEST_2="\nError occurred during CI test"
-            VALIDATION_ERRORS_CI_TEST_3="\nError occurred during CI test"
           fi
 
           MSG="*CI Reliability Test $EMOJI_RESULT_OVERALL*"
