fix(ci): helm test as stage B build (#2946)
This adds the helm directory as it's own stage B build.
That means the tests are now triggered in every PR and main build, and
not within the release pipeline anymore.

Ref: SRX-UREFYC

diff --git a/.github/workflows/ci-reliability-snippet.yml b/.github/workflows/ci-reliability-snippet.yml
--- a/.github/workflows/ci-reliability-snippet.yml
+++ b/.github/workflows/ci-reliability-snippet.yml
@@ -36,6 +36,9 @@ on:
       modify_readme:
         required: true
         type: boolean
+      inject_helm_error:
+        required: true
+        type: boolean
       inject_integration_tests_error:
         required: true
         type: boolean
@@ -96,6 +99,10 @@ jobs:
         if: inputs.modify_readme == true
         run: |
           echo -e "\nTest reliability" >> README.md
+      - name: Modify Helm
+        if: inputs.inject_helm_error == true
+        run: |
+          echo -e "\nInvalid:yaml:construct:no:way:this:is:valid" >> charts/kuberpult/templates/cd-service.yaml
       - name: Inject error in integration tests
         if: inputs.inject_integration_tests_error == true
         run: |
@@ -177,10 +184,10 @@ jobs:
         with:
           name: validation-errors-${{ inputs.test_id }}.zip
           path: validation-errors.txt
-  check-linting-errors:
+  check-go-linting-errors:
     # check if the golangci-lint detects the injected linting error in cd-service
     # this check is only run when inputs.inject_linting_error is set to true
-    name: "Check linting errors"
+    name: "Handle go linting errors"
     if: ${{ inputs.inject_linting_error == true && always() }}
     needs: [trigger-ci]
     runs-on: ubuntu-latest
@@ -193,7 +200,7 @@ jobs:
         with:
           name: linting-report-services_cd-service-5.zip
           path: linting-report
-      - name: "Check linting errors"
+      - name: "Check go linting errors"
         run: |
           touch validation-errors.txt
           if [[ "${{ needs.trigger-ci.result }}" != "failure" ]]; then
@@ -201,6 +208,38 @@ jobs:
           elif [[ ! -n $(grep "services/cd-service/cmd/server/main.go" linting-report/.golangci_lint.log | grep "const unusedConst is unused") ]]; then
             # the injected linting error is not correctly detected: unused const "unusedConst" in main.go file
             echo "Linting error not detected" >> validation-errors.txt
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Upload validation errors
+        id: upload-validation-errors
+        uses: actions/upload-artifact@v6
+        with:
+          name: validation-errors-${{ inputs.test_id }}.zip
+          path: validation-errors.txt
+  check-helm-linting-errors:
+    # check if helm test detects the injected linting error in the yaml
+    name: "Handle helm linting errors"
+    if: ${{ inputs.inject_helm_error == true && always() }}
+    needs: [trigger-ci]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+      - name: Download helm-lint report
+        uses: actions/download-artifact@v6
+        with:
+          name: linting-report-charts_kuberpult-6.zip
+          path: linting-report
+      - name: "Check helm linting errors"
+        run: |
+          touch validation-errors.txt
+          if [[ "${{ needs.trigger-ci.result }}" != "failure" ]]; then
+            echo "CI build should have failed due to linting error" >> validation-errors.txt
+          fi
+          if ! grep -q -F "[ERROR] templates/cd-service.yaml" linting-report/helm_lint.log ; then
+            echo "Helm linting error not detected" >> validation-errors.txt
           fi
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -220,6 +259,11 @@ jobs:
         with:
           fetch-depth: 0
       - name: "Check integration tests errors"
+        uses: actions/download-artifact@v6
+        with:
+          name: linting-report-charts_kuberpult-6.zip
+          path: linting-report
+      - name: "Check helm linting errors"
         run: |
           touch validation-errors.txt
           if [[ "${{ needs.trigger-integration-tests.result }}" != "failure" && "${{ needs.trigger-integration-tests.result }}" != "cancelled" ]]; then
diff --git a/.github/workflows/ci-reliability.yml b/.github/workflows/ci-reliability.yml
--- a/.github/workflows/ci-reliability.yml
+++ b/.github/workflows/ci-reliability.yml
@@ -22,6 +22,7 @@ jobs:
 
             modify_readme: false
             inject_linting_error: false
+            inject_helm_error: false
             inject_integration_tests_error: false
 
             check_new_images: true
@@ -37,6 +38,7 @@ jobs:
 
             modify_readme: false
             inject_linting_error: false
+            inject_helm_error: false
             inject_integration_tests_error: false
 
             check_new_images: true
@@ -52,6 +54,7 @@ jobs:
 
             modify_readme: false
             inject_linting_error: false
+            inject_helm_error: false
             inject_integration_tests_error: false
 
             check_new_images: true
@@ -67,6 +70,7 @@ jobs:
 
             modify_readme: true
             inject_linting_error: false
+            inject_helm_error: false
             inject_integration_tests_error: false
 
             check_new_images: true
@@ -83,12 +87,31 @@ jobs:
 
             modify_readme: false
             inject_linting_error: true
+            inject_helm_error: false
             inject_integration_tests_error: false
 
             check_new_images: false
             expect_cd: false
             expect_fe: false
             expect_export: false
+
+          - id: "6" # test helm reliability
+            source_branch: automated/ci-reliability/ci-test-6
+            modify_pkg: false
+            modify_cd: false
+            modify_fe: false
+            modify_export: false
+
+            modify_readme: false
+            inject_linting_error: false
+            inject_helm_error: true
+            inject_integration_tests_error: false
+
+            check_new_images: false
+            expect_cd: false
+            expect_fe: false
+            expect_export: false
+
           - id: "7" # test integration test reliability
             source_branch: automated/ci-reliability/ci-test-7
             modify_pkg: false
@@ -98,6 +121,7 @@ jobs:
 
             modify_readme: false
             inject_linting_error: false
+            inject_helm_error: false
             inject_integration_tests_error: true
 
             check_new_images: false
@@ -108,6 +132,7 @@ jobs:
     with:
       test_id: ${{ matrix.id }}
       source_branch: ${{ matrix.source_branch }}
+      base_branch: ${{ github.ref }} # use the current ref, in case we trigger from a specific branch
 
       modify_pkg: ${{ matrix.modify_pkg }}
       modify_cd_service: ${{ matrix.modify_cd }}
@@ -116,6 +141,7 @@ jobs:
       
       modify_readme: ${{ matrix.modify_readme }}
       inject_linting_error: ${{ matrix.inject_linting_error }}
+      inject_helm_error: ${{ matrix.inject_helm_error }}
       inject_integration_tests_error: ${{ matrix.inject_integration_tests_error }}
 
       check_new_images: ${{ matrix.check_new_images }}
@@ -158,7 +184,13 @@ jobs:
         uses: actions/download-artifact@v6
         with:
           name: validation-errors-5.zip
-          path: validation-errors-5          
+          path: validation-errors-5
+      - name: Download validation errors for Test 6
+        continue-on-error: true
+        uses: actions/download-artifact@v6
+        with:
+          name: validation-errors-6.zip
+          path: validation-errors-6
       - name: Download validation errors for Test 7
         continue-on-error: true
         uses: actions/download-artifact@v6
@@ -173,6 +205,7 @@ jobs:
           EMOJI_RESULT_CI_TEST_3="✅"
           EMOJI_RESULT_CI_TEST_4="✅"
           EMOJI_RESULT_CI_TEST_5="✅"
+          EMOJI_RESULT_CI_TEST_6="✅"
           EMOJI_RESULT_CI_TEST_7="✅"
 
           # If the validation-errors artifact is not uploaded, it means the CI test failed
@@ -181,6 +214,7 @@ jobs:
           VALIDATION_ERRORS_CI_TEST_3=$(cat validation-errors-3/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
           VALIDATION_ERRORS_CI_TEST_4=$(cat validation-errors-4/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
           VALIDATION_ERRORS_CI_TEST_5=$(cat validation-errors-5/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
+          VALIDATION_ERRORS_CI_TEST_6=$(cat validation-errors-6/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
           VALIDATION_ERRORS_CI_TEST_7=$(cat validation-errors-7/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
 
           if [[ -n "$VALIDATION_ERRORS_CI_TEST_1" ]]; then
@@ -205,6 +239,11 @@ jobs:
 
           if [[ -n "$VALIDATION_ERRORS_CI_TEST_5" ]]; then
             EMOJI_RESULT_CI_TEST_5="❌"
+            EMOJI_RESULT_OVERALL="❌"
+          fi
+
+          if [[ -n "$VALIDATION_ERRORS_CI_TEST_6" ]]; then
+            EMOJI_RESULT_CI_TEST_6="❌"
             EMOJI_RESULT_OVERALL="❌"
           fi
 
@@ -240,6 +279,11 @@ jobs:
             MSG+="\n\`\`\`$VALIDATION_ERRORS_CI_TEST_5\n\`\`\`"
           fi
 
+          MSG+="\n\n*Test 6:* $EMOJI_RESULT_CI_TEST_6 error in helm test detected"
+          if [ -n "$VALIDATION_ERRORS_CI_TEST_6" ]; then
+            MSG+="\n\`\`\`$VALIDATION_ERRORS_CI_TEST_6\n\`\`\`"
+          fi
+
           MSG+="\n\n*Test 7:* $EMOJI_RESULT_CI_TEST_7 error in integration test is detected"
           if [ -n "$VALIDATION_ERRORS_CI_TEST_7" ]; then
             MSG+="\n\`\`\`$VALIDATION_ERRORS_CI_TEST_7\n\`\`\`"
@@ -247,6 +291,7 @@ jobs:
 
           MSG+="\n\n*🔗 View in GitHub Action:* $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
 
+          echo "${MSG}"
           curl \
             --request POST \
             --header "Content-Type: application/json" \
