fix: add CI reliability test for integration-test (#2953)
Ref:
[SRX-S66VRR](https://revolution.dev/app/-JqFGExX46gs9mH7vxR5/-M37cZx7XYoOvQ5Mmcir/STORY/-OnVvaSOsN2_srLWsRr5/)

This reliability test intentionally modifies the Postgres port during
integration testing. As a result, all integration tests are expected to
fail or timeout, which should ultimately cause the entire CI pipeline to
fail.

diff --git a/.github/workflows/ci-reliability.yml b/.github/workflows/ci-reliability.yml
--- a/.github/workflows/ci-reliability.yml
+++ b/.github/workflows/ci-reliability.yml
@@ -22,6 +22,7 @@ jobs:
 
             modify_readme: false
             inject_linting_error: false
+            inject_integration_tests_error: false
 
             check_new_images: true
             expect_cd: true
@@ -36,6 +37,7 @@ jobs:
 
             modify_readme: false
             inject_linting_error: false
+            inject_integration_tests_error: false
 
             check_new_images: true
             expect_cd: false
@@ -50,6 +52,7 @@ jobs:
 
             modify_readme: false
             inject_linting_error: false
+            inject_integration_tests_error: false
 
             check_new_images: true
             expect_cd: true
@@ -64,6 +67,7 @@ jobs:
 
             modify_readme: true
             inject_linting_error: false
+            inject_integration_tests_error: false
 
             check_new_images: true
             expect_cd: false
@@ -79,6 +83,22 @@ jobs:
 
             modify_readme: false
             inject_linting_error: true
+            inject_integration_tests_error: false
+
+            check_new_images: false
+            expect_cd: false
+            expect_fe: false
+            expect_export: false
+          - id: "7" # test integration test reliability
+            source_branch: automated/ci-reliability/ci-test-7
+            modify_pkg: false
+            modify_cd: false
+            modify_fe: false
+            modify_export: false
+
+            modify_readme: false
+            inject_linting_error: false
+            inject_integration_tests_error: true
 
             check_new_images: false
             expect_cd: false
@@ -96,6 +116,7 @@ jobs:
       
       modify_readme: ${{ matrix.modify_readme }}
       inject_linting_error: ${{ matrix.inject_linting_error }}
+      inject_integration_tests_error: ${{ matrix.inject_integration_tests_error }}
 
       check_new_images: ${{ matrix.check_new_images }}
       expect_new_image_cd_service: ${{ matrix.expect_cd }}
@@ -138,6 +159,12 @@ jobs:
         with:
           name: validation-errors-5.zip
           path: validation-errors-5          
+      - name: Download validation errors for Test 7
+        continue-on-error: true
+        uses: actions/download-artifact@v6
+        with:
+          name: validation-errors-7.zip
+          path: validation-errors-7
       - name: Notify results
         run: |
           EMOJI_RESULT_OVERALL="✅"
@@ -146,6 +173,7 @@ jobs:
           EMOJI_RESULT_CI_TEST_3="✅"
           EMOJI_RESULT_CI_TEST_4="✅"
           EMOJI_RESULT_CI_TEST_5="✅"
+          EMOJI_RESULT_CI_TEST_7="✅"
 
           # If the validation-errors artifact is not uploaded, it means the CI test failed
           VALIDATION_ERRORS_CI_TEST_1=$(cat validation-errors-1/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
@@ -153,6 +181,7 @@ jobs:
           VALIDATION_ERRORS_CI_TEST_3=$(cat validation-errors-3/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
           VALIDATION_ERRORS_CI_TEST_4=$(cat validation-errors-4/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
           VALIDATION_ERRORS_CI_TEST_5=$(cat validation-errors-5/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
+          VALIDATION_ERRORS_CI_TEST_7=$(cat validation-errors-7/validation-errors.txt 2> /dev/null || echo "\nError occurred during CI build")
 
           if [[ -n "$VALIDATION_ERRORS_CI_TEST_1" ]]; then
             EMOJI_RESULT_CI_TEST_1="❌"
@@ -176,6 +205,11 @@ jobs:
 
           if [[ -n "$VALIDATION_ERRORS_CI_TEST_5" ]]; then
             EMOJI_RESULT_CI_TEST_5="❌"
+            EMOJI_RESULT_OVERALL="❌"
+          fi
+
+          if [[ -n "$VALIDATION_ERRORS_CI_TEST_7" ]]; then
+            EMOJI_RESULT_CI_TEST_7="❌"
             EMOJI_RESULT_OVERALL="❌"
           fi
 
@@ -204,6 +238,11 @@ jobs:
           MSG+="\n\n*Test 5:* $EMOJI_RESULT_CI_TEST_5 linting error in cd-service is detected"
           if [ -n "$VALIDATION_ERRORS_CI_TEST_5" ]; then
             MSG+="\n\`\`\`$VALIDATION_ERRORS_CI_TEST_5\n\`\`\`"
+          fi
+
+          MSG+="\n\n*Test 7:* $EMOJI_RESULT_CI_TEST_7 error in integration test is detected"
+          if [ -n "$VALIDATION_ERRORS_CI_TEST_7" ]; then
+            MSG+="\n\`\`\`$VALIDATION_ERRORS_CI_TEST_7\n\`\`\`"
           fi
 
           MSG+="\n\n*🔗 View in GitHub Action:* $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
